### ISSUE TITLE
do you have advice on saving to svg?

### ISSUE THREAD

**Issue by sklise** [runemadsen/rune.js#11]
Here's a [gist](https://gist.github.com/sklise/cf3e3d3602e600bf5fd3) I wrote to get output from a `Rune` to save to and svg.

I had trouble with the `getEl()` function, when I passed it to [vdom-to-html](https://github.com/nthtran/vdom-to-html/blob/master/index.js) I got empty string :cry: so I found `.renderer.tree` which worked. 

Is there a better way you've used to save to files?

**Comment by runemadsen** [comment]
Good question. My students use the browser while developing their code, and then use SVG Crowbar (a Chrome extension that will download any SVG's on a page) to get their results to a singular SVG file.

http://nytimes.github.io/svg-crowbar/

Will that work?
