### ISSUE TITLE
Transform translate(x y) support?

### ISSUE THREAD

**Issue by vorg** [runemadsen/rune.js#28]
Both `scale` and `rotate` modify elements `transform` property. There is no way to add `transform` though. Even that `move(x, y)` exists it's not always what I need:

Move + rotate:
![screen shot 2017-08-11 at 18 29 29 copy](https://user-images.githubusercontent.com/171001/29225630-fc4f9ac2-7ec6-11e7-9206-b9720ce7dcc1.png)

Move + transform (simulated with parent group move + elem rotate)
![screen shot 2017-08-11 at 18 53 44 copy](https://user-images.githubusercontent.com/171001/29225580-cbce2dd2-7ec6-11e7-9107-b6c52886a2db.jpg)

**Comment by runemadsen** [comment]
Hi @vorg. Can you post the two code examples? That will help me understand your issue better. Thx

**Comment by vorg** [comment]
## move + rotate

Completely wrong

<img width="339" alt="screen shot 2017-08-12 at 21 15 59" src="https://user-images.githubusercontent.com/171001/29243947-fb1eb68c-7fa3-11e7-8068-51c64a9d657c.png">

```javascript

var r = new Rune({
  container: 'body',
  width: 400,
  height: 400
})

r.rect(0, 0, r.width, r.height).fill(250, 250, 100).stroke(false)
for (var i = 0; i < 10; i++) {
  for (var j = 0; j < 10; j++) {
    var x = i * 40 + 20
    var y = j * 40 + 20
    r.rect(-15, -5, 30, 10).move(x, y)
      .fill(100, 100, 255)
      .stroke(false)
      .rotate(45)
  }
}

r.draw()
```

## move + rotate with offset

Rects are off the center 

<img width="338" alt="screen shot 2017-08-12 at 21 16 04" src="https://user-images.githubusercontent.com/171001/29243933-aa3d3748-7fa3-11e7-9454-83d2fcdf6728.png">

```javascript
// move + rotate + offset

var r2 = new Rune({
  container: 'body',
  width: 400,
  height: 400
})

r2.rect(0, 0, r.width, r.height).fill(250, 250, 100).stroke(false)

for (var i = 0; i < 10; i++) {
  for (var j = 0; j < 10; j++) {
    var x = i * 40 + 20
    var y = j * 40 + 20
    r2.rect(-15, -5, 30, 10).move(x, y)
      .fill(100, 100, 255)
      .stroke(false)
      .rotate(45, x, y)
  }
}

r2.draw()
```

# translater + rotate

Perfect on spot

<img width="339" alt="screen shot 2017-08-12 at 21 16 13" src="https://user-images.githubusercontent.com/171001/29243959-35f4a0a0-7fa4-11e7-9e8f-99c62376fe91.png">

```javascript
var r3 = new Rune({
  container: 'body',
  width: 400,
  height: 400
})

r3.rect(0, 0, r.width, r.height).fill(250, 250, 100).stroke(false)

for (var i = 0; i < 10; i++) {
  for (var j = 0; j < 10; j++) {
    var x = i * 40 + 20
    var y = j * 40 + 20
    r3.rect(-15, -5, 30, 10)
      .fill(100, 100, 255)
      .stroke(false)
  }
}

r3.draw()
var rects = document.querySelectorAll('svg')[2].querySelectorAll('rect')
rects = Array.prototype.slice.call(rects)
rects.shift() // skip background rect
rects.forEach((rect, idx) => {
  var i = idx % 10
  var j = Math.floor(idx / 10)
  var x = i * 40 + 20
  var y = j * 40 + 20
  rect.setAttribute('transform', `translate(${x} ${y}) rotate(45)`)
})
```

**Comment by runemadsen** [comment]
Just getting back to this. This is all expected behavior in Rune.js. Like P5 and Processing, `rotate()` will always rotate around the 0,0 origin point, unless you specify a location to rotate around. It's simply a matter of tweaking your numbers to achieve the design that you want.

```js
var r = new Rune({
  container: "body",
  width: 400,
  height: 400
});

r.rect(0, 0, r.width, r.height).fill(250, 250, 100).stroke(false)

for (var i = 0; i < 10; i++) {
  for (var j = 0; j < 10; j++) {
    var x = i * 40 + 15
    var y = j * 40 + 5
    r.rect(0, 0, 30, 10)
      .move(x, y)
      .fill(100, 100, 255)
      .stroke(false)
      .rotate(45, x, y)
  }
}

r.draw();
```

<img width="400" alt="pattern" src="https://user-images.githubusercontent.com/192021/30264807-b7da26d8-970c-11e7-9b5e-b009e3244da2.png">
