### ISSUE TITLE
Why not D3?

### ISSUE THREAD

**Issue by stuartpb** [runemadsen/rune.js#36]
https://runemadsen.github.io/rune.js/about.html#why-not- lists the "why not" of this library, and lists several inspirations for it including D3, but doesn't describe what this library has that D3 doesn't.

**Comment by runemadsen** [comment]
Good point. I should add that. I think the biggest thing is that to use D3, you need to know about the DOM and the SVG element and its attributes. To use Rune.js, you don't need to. So people coming from Processing / P5.js will pick up Rune.js while D3 will be quite a challenge. I have taught D3 to students before, and its API is highly cryptic to beginners. And then on top of that come things such as grid system, debug mode, etc.
