### ISSUE TITLE
Calling pause does not pause animation.

### ISSUE THREAD

**Issue by arlando** [runemadsen/rune.js#4]
Not sure whats going on but when I call pause:
```javascript
let r = new Rune;
r.play();
r.on('draw', fc => {
    // Do some wicked animation stuff.
    r.pause();
});
```
Does not actually stop the 'draw' event. However if I do:

```javascript
let r = new Rune;
r.play();
r.on('draw', fc => {
  // More wicked...
});
r.pause();
```
This seems to work.

**Comment by runemadsen** [comment]
Thanks for reporting this. It was a small problem related to `requestAnimationframe` being renewed before `cancelAnimationframe` was called, thus cancelling cancelling a non-existing frame. I just fixed it, and I'll publish a `0.2.4` release later today. :+1:

**Comment by runemadsen** [comment]
`0.2.4` has been released!

**Comment by arlando** [comment]
Grazie!
