### ISSUE TITLE
Question: How to obtain SVG code within Node.js

### ISSUE THREAD

**Issue by fabianmoronzirfas** [runemadsen/rune.js#47]
Hi,

I'm trying to understand how to obtain the SVG markup when using the library in Node.js. I can't find anything about that.

**Comment by runemadsen** [comment]
As stated in the documentation, you can get the SVG DOM element by accessing the `el` attribute of the `Rune` instance. So you can just do something like this to get a string representation of the SVG in Node:

```js
console.log(r.el.innerHTML)
```

In Node, the `el` element is a fake DOM element created with the `min-document` package, so you can take a look at the methods supported here:
https://www.npmjs.com/package/min-document

**Comment by fabianmoronzirfas** [comment]
I tried that. When running this:

```js
const Rune = require("rune.js");

const r = new Rune({
  container: "body",
  width: 500,
  height: 400
});

r.rect(0, 0, 200, 200).fill(0, 0, 255);
r.draw();
console.log(r.el.innerHTML);
```

r.el.innerHTML is undefined

**Comment by runemadsen** [comment]
Ah, I guess `min-document` doesn't support `innerHTML`. Then just call `toString()` on the el:

```js
const Rune = require("rune.js");

var r = new Rune({
  container: "body",
  width: 500,
  height: 400
});

r.rect(0, 0, 200, 200).fill(0, 0, 255);

r.draw();

console.log(r.el.toString());
```

**Comment by fabianmoronzirfas** [comment]
Thank you!
