### ISSUE TITLE
Polygons and Paths initial (x, y) seems to be ignored

### ISSUE THREAD

**Issue by peregrinogris** [runemadsen/rune.js#53]
Seems like the initial position given to both polygons and paths is ignored when returning information computed on the shapes (`centroid`, `vectorAtLength`, etc). I don't know if this is by design or an actual bug, I'd be happy to try fixing it.

Code to reproduce:
```js
import Rune from 'rune.js'

const r = new Rune({
  container: "body",
  width: 500,
  height: 500
});

const poly = r.polygon(150, 150)
      .lineTo(0, 0)
      .lineTo(200, 0)
      .lineTo(200, 200)
      .lineTo(0, 200);

const centroid = poly.centroid();

// Debug
r.line(0, 250, 500, 250).stroke('red')
r.line(250, 0, 250, 500).stroke('red')

r.circle(centroid.x, centroid.y, 10).fill('orange');
r.draw();
```

Result:
![Screenshot from 2022-03-03 10-28-19](https://user-images.githubusercontent.com/115484/156574565-16157cd4-bd43-4146-ab8a-df5929ba1423.png)

**Comment by runemadsen** [comment]
Hi @peregrinogris. Thanks so much for the feedback! I actually think this is intended. The `centroid()` function will always return the internal centroid, so you will have to add the `x` and `y` of the shape to get the centroid to place it directly in the centroid of the shape. The reasoning for this is that a shape can belong to any number of groups with their own `x` and `y`, so all shapes simply return their centroid in internal coordinates.

**Comment by peregrinogris** [comment]
> The reasoning for this is that a shape can belong to any number of groups with their own `x` and `y`, so all shapes simply return their centroid in internal coordinates.

Ah, that makes sense. I was curious about the reasoning because it seemed on purpose, thanks for the clarification!
