### ISSUE TITLE
Bezier curve debug points ignoring moveTo

### ISSUE THREAD

**Issue by peregrinogris** [runemadsen/rune.js#54]
When debug is enabled the control points and tangents don't take into account possible moves in the current path.

**Code to reproduce:**
```js
import Rune from "rune.js";

const r = new Rune({
  container: "#app",
  width: 300,
  height: 300,
  debug: true
});

r.path(0, 0)
  .moveTo(100, 50)
  .curveTo(100, 150, 200, 150, 200, 50)
  .stroke("blue")
  .fill("none")
  .closePath();

r.draw();
```

**Result:**
![Screenshot from 2022-03-04 11-38-45](https://user-images.githubusercontent.com/115484/156783008-68a0d0b2-acc7-4839-a308-31fd1dfac9e3.png)

**Comment by runemadsen** [comment]
Hi @peregrinogris. This is actually behaving as expected. You will see highlighted the two control points at their correct positions as well as the end point of the bezier. I know this is a bit different from how programs from Illustrator show handles, but I think it makes sense when you think about the values you input for the `curveTo` command which are all shown in the debug view.

**Comment by peregrinogris** [comment]
> I know this is a bit different from how programs from Illustrator show handles, but I think it makes sense when you think about the values you input for the `curveTo` command which are all shown in the debug view.

Thanks for the explanation. From what you say then, debug view for bezier curves seems to be about having visual cues on what parameters `curveTo` was called with, rather than visual aids to understand why the bezier curve is rendering in that particular way 👍🏼
